name: Build and Deploy Affected Apps

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    # Checkout branch
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Install dependencies
      - name: Install Dependencies
        run: npm ci

      # Check which apps have been affected
      - name: Check Affected Apps
        run: npx nx affected:apps --base=HEAD~1 --plain

      # Build affected apps
      - name: Build Affected Apps
        run: npx nx affected --base=HEAD~1 --target=build --prod

      # Deploy affected apps
      - name: Deploy Affected Apps
        uses: appleboy/scp-action@master
        with:
          overwrite: true
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: 'dist/apps'
          strip_components: 2
          target: '/var/www/html/trade-invest'